"""kb — Diff-only KB writer with fingerprint dedup."""

import hashlib
from pathlib import Path
from typing import Any

from sdlc.audit import AuditEventType, AuditLogger
from sdlc.kb.fingerprint import compute_kb_fingerprint
from sdlc.kb.knowledge_base import KnowledgeBase
from sdlc.kb.models import KBDeltaResult
from sdlc.utils.exceptions import KBWriteConflictError
from sdlc.utils.paths import ensure_dir
from sdlc.utils.time import format_iso, now_utc
from sdlc.utils.yaml_io import load_yaml, save_yaml


class KBWriter:
    """Writes KB updates using diff-only semantics (append or update).

    Key invariants:
    * Don't overwrite human edits (conventions.md is human-only).
    * Diff-only: append mode never modifies original content.
    * Idempotent: writing the same stage output twice yields the same result.
    * Fingerprint dedup: same content is never written twice.
    * Audit complete: every write (or skip) gets an audit event.
    """

    # Files that must never be touched by the writer.
    HUMAN_ONLY: set[str] = {"conventions.md"}

    def __init__(
        self,
        kb: KnowledgeBase,
        audit: AuditLogger | None = None,
    ) -> None:
        self.kb = kb
        self.audit = audit
        self._written_targets: set[str] = set()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def update_after_stage(
        self,
        stage_id: str,
        updates: list[dict[str, Any]],
    ) -> list[KBDeltaResult]:
        """Write KB updates after *stage_id* completes.

        Each item in *updates* is a dict with keys:
        ``target``, ``operation``, ``content``, ``template`` (optional).
        """
        deltas: list[KBDeltaResult] = []
        for upd in updates:
            delta = self._build_delta(upd)
            if self._should_write(delta):
                self._write_one(delta)
            # Whether written or skipped, include in results.
            deltas.append(delta)
        return deltas

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _build_delta(self, upd: dict[str, Any]) -> KBDeltaResult:
        """Construct a :class:`KBDeltaResult` from a raw update dict."""
        target: str = upd["target"]
        operation: str = upd["operation"]
        content: str = upd.get("content", "")
        return KBDeltaResult(
            target=target,
            operation=operation,
            content=content,
            fingerprint="",  # computed after write via compute_kb_fingerprint(path)
        )

    def _should_write(self, delta: KBDeltaResult) -> bool:
        """Return ``True`` if *delta* should be written to disk."""
        # 1. Human-only files are never written.
        if delta.target in self.HUMAN_ONLY:
            delta.skipped = True
            delta.skip_reason = f"{delta.target} is human-only"
            self._emit_audit(delta, "skip_human_only")
            return False

        # 2. Target dedup: don't write to the same target twice in one batch.
        if delta.target in self._written_targets:
            delta.skipped = True
            delta.skip_reason = "duplicate target"
            self._emit_audit(delta, "skip_dedup")
            return False

        return True

    def _write_one(self, delta: KBDeltaResult) -> None:
        """Persist *delta* to disk according to its operation type."""
        file_path = self.kb.root / delta.target
        ensure_dir(file_path.parent)

        if delta.operation == "append":
            self._write_append(file_path, delta)
        elif delta.operation == "update":
            self._write_update(file_path, delta)
        else:
            raise KBWriteConflictError(
                f"Unknown KB write operation: {delta.operation}",
                details={"target": delta.target, "operation": delta.operation},
            )

        # Compute fingerprint from the file on disk (bytes-level consistency)
        if not delta.skipped:
            delta.fingerprint = compute_kb_fingerprint(file_path)
            self._written_targets.add(delta.target)
        self._emit_audit(delta, "written")

        # Refresh the in-memory layer index if the file is already tracked.
        self._refresh_layer(delta.target, file_path)

    def _write_append(self, file_path: Path, delta: KBDeltaResult) -> None:
        """Append *delta.content* to *file_path* with a section header."""

        # Compute content fingerprint for idempotency check.
        content_hash = hashlib.sha256(delta.content.encode("utf-8")).hexdigest()

        section_header = (
            f"\n\n---\n<!-- Auto-generated by SDLC stage "
            f"| fingerprint={content_hash} "
            f"| ts={format_iso(now_utc())} -->\n\n"
        )

        if file_path.exists():
            existing = file_path.read_text(encoding="utf-8")
            # Idempotency: if the content hash is already present, don't append.
            if content_hash in existing:
                delta.skipped = True
                delta.skip_reason = "content already present (idempotent)"
                return
            new_content = existing + section_header + delta.content
        else:
            new_content = section_header + delta.content

        # Atomic write: write to temp file then rename
        tmp = file_path.with_suffix(file_path.suffix + ".tmp")
        tmp.write_text(new_content, encoding="utf-8")
        tmp.rename(file_path)

    def _write_update(self, file_path: Path, delta: KBDeltaResult) -> None:
        """Update a YAML (or JSON) file using ruamel.yaml to preserve structure."""
        if not file_path.exists():
            # For update mode the file must already exist.
            raise KBWriteConflictError(
                f"Cannot update non-existent KB file: {delta.target}",
                details={"target": delta.target},
            )

        layer = self.kb.layers.get(delta.target)
        if layer is not None and layer.type == "yaml":
            data = load_yaml(file_path)
            # Merge new content into existing data.
            import json

            new_data = json.loads(delta.content) if delta.content.strip() else {}
            if isinstance(data, dict) and isinstance(new_data, dict):
                data.update(new_data)
            # Atomic write for YAML
            tmp = file_path.with_suffix(file_path.suffix + ".tmp")
            save_yaml(tmp, data)
            tmp.rename(file_path)
        else:
            # For markdown / JSON files, fall back to full rewrite (atomic).
            tmp = file_path.with_suffix(file_path.suffix + ".tmp")
            tmp.write_text(delta.content, encoding="utf-8")
            tmp.rename(file_path)

    def _refresh_layer(self, name: str, file_path: Path) -> None:
        """Refresh the KB layer entry after a write."""
        from sdlc.kb.knowledge_base import _detect_type
        from sdlc.kb.models import KBLayer
        from sdlc.utils.fingerprint import file_fingerprint

        try:
            fp = file_fingerprint(file_path)
            stat = file_path.stat()
            self.kb.layers[name] = KBLayer(
                name=name,
                type=_detect_type(name),
                path=file_path.resolve(),
                fingerprint=fp,
                last_modified=format_iso(now_utc()),
                size_bytes=stat.st_size,
            )
        except (FileNotFoundError, OSError):
            pass

    def _emit_audit(self, delta: KBDeltaResult, action: str) -> None:
        """Emit an audit event for *delta* / *action*."""
        if self.audit is None:
            return
        self.audit.emit(
            AuditEventType.KB_UPDATED,
            payload={
                "action": action,
                "target": delta.target,
                "operation": delta.operation,
                "fingerprint": delta.fingerprint,
                "skipped": delta.skipped,
                "skip_reason": delta.skip_reason,
            },
        )
