from enum import StrEnum


class AuditEventType(StrEnum):
    PIPELINE_START = "pipeline_start"
    PIPELINE_END = "pipeline_end"
    ENTRY_DETECTED = "entry_detected"
    ADAPTER_DETECTED = "adapter_detected"
    PROFILE_RESOLVED = "profile_resolved"
    PIPELINE_BUILT = "pipeline_built"
    STAGE_START = "stage_start"
    STAGE_END = "stage_end"
    ARTIFACT_CREATED = "artifact_created"
    KB_UPDATED = "kb_updated"
    KB_INIT = "kb_init"
    RULE_VIOLATION = "rule_violation"
    RULE_CHECK = "rule_check"
    GATE_TRIGGERED = "gate_triggered"
    GATE_DECISION = "gate_decision"
    LLM_CALLED = "llm_called"
    LLM_FALLBACK = "llm_fallback"
    LLM_CACHED = "llm_cached"
    SUBAGENT_INVOKED = "subagent_invoked"
    MCP_CALLED = "mcp_called"
    SKILL_USED = "skill_used"
    FILE_WRITTEN = "file_written"
    ERROR = "error"
    RESUME = "resume"
    COST_EXCEEDED = "cost_exceeded"
    SNAPSHOT_TAKEN = "snapshot_taken"
    CONFIG_LOADED = "config_loaded"
